 
GET https://3000-kpishnik-atmycoding-fd4hu0rua1y.ws-eu47.gitpod.io


###

POST https://google.com

###
DELETE http://localhost:3000/login


###
POST https://3000-kpishnik-atmycoding-fd4hu0rua1y.ws-eu47.gitpod.io/register 
Content-Type: application/json

{
"email": "s@s",
"userName": "s",
"password": "s",
"password2": "s"
}

###
POST https://3000-kpishnik-atmycoding-fd4hu0rua1y.ws-eu47.gitpod.io/login
Content-Type: application/json

{
"email": "Ukraine@wins",
"password": "UW"
}

###
POST https://3000-kpishnik-atmycoding-fd4hu0rua1y.ws-eu47.gitpod.io/user/password
Content-Type: application/json

{
"newPass": "UW",
"newPass2": "UW",
"password": "q"
}


###
POST https://3000-kpishnik-atmycoding-fd4hu0rua1y.ws-eu47.gitpod.io/user/email
Content-Type: application/json

{
"email": "Ukraine@wins",
"password": "q"
}


###
POST https://3000-kpishnik-atmycoding-fd4hu0rua1y.ws-eu47.gitpod.io/user/username
Content-Type: application/json

{
"username": "Ukraine wins",
"password": "q"
}