 
GET https://3000-kpishnik-atmycoding-fd4hu0rua1y.ws-eu46.gitpod.io


###

POST https://google.com



### 

POST https://3000-kpishnik-atmycoding-fd4hu0rua1y.ws-eu46.gitpod.io/login
Content-Type: application/json

{
"email": "antaresstat@gmailcom",
"password": "23"
}

###
DELETE http://localhost:3000/login


###
POST https://3000-kpishnik-atmycoding-fd4hu0rua1y.ws-eu46.gitpod.io/register 
Content-Type: application/json

{
"email": "antt@gmail.com",
"userName": "as",
"password": "5",
"password2": "5"
}
